import Head from 'next/head';
import { ConnectButton } from '@/components/ConnectButton';
import abi from '../contracts/out/debug/contracts-abi.json';
import { useContract } from '@/hooks/useContract';
import { useState } from 'react';

const CONTRACT_ID =
  '0x7d55514ef24ae04db4254e7eb611a7761c0f0520164ab50e47fcd837bd7a86ee';

export default function Home() {
  const [contract] = useContract(CONTRACT_ID, abi);
  const [value, setValue] = useState<string>();

  const onReadPress = async () => {
    if (contract) {
      const { value } = await contract.functions.test_function().simulate();
      console.log({
        value,
      });
      setValue(`${value}`);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <ConnectButton />

        {contract && (
          <div>
            <span>Contract ID: {contract.id.toB256()}</span>

            <button onClick={onReadPress}>
              Read value from `test_function`
            </button>

            {value && (
              <div>
                <span>Value: {value}</span>
              </div>
            )}
          </div>
        )}
      </main>
    </>
  );
}
